### ISSUE TITLE
Gamemodes ToDo

### ISSUE THREAD

**Issue by LizzyFleckenstein03** [EliasFleckenstein03/elidragon_v2#7]
Finish before going online for the first time:
- [ ] creative (add streets generation + plot claiming system)
- [ ] survival (plot + trading system etc.)
- [ ] skyblock (basically everything is missing rn, port lots of code from skycraft)
- [ ] lobby (make clickable redirect entities and a fixed hotbar)
- [ ] (maybe) anarchy

Nice to have / planned for the future:
- [ ] minigames
- [ ] citybuild
- [ ] (maybe) factions
- [ ] cosmetics for the lobby
- [ ] quests for skyblock
